name: 1-feature-test-lint

on:
  push:
    branches:
      - 'feature/**'

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:      
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        
      - name: Checkout
        uses: actions/checkout@v3


      - name: pip install
        run:  python -m pip install -r requirements.txt
        
      - name: Test app
        run:  python app/manage.py wait_for_db && python aap/manage.py test && flake8


      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v2
      
      # - name: Terraform fmt
      #   run: terraform fmt
