name: 1-feature-test-lint

on:
  push:
    branches:
      - 'feature/**'

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: juliazuin/recipe-app-api-devops

      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

        # Display the Python version being used
      - name: Test app
        run:  python manage.py wait_for_db && python manage.py test && flake8


      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v2
      
      # - name: Terraform fmt
      #   run: terraform fmt
